# Generated by Django 4.1.6 on 2023-02-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('size', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=100)),
                ('in_progress', models.BooleanField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
