# Generated by Django 4.1.6 on 2023-02-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
